spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MongoDBDialect
        format_sql: true

server:
  port: 8081

mendonca:
  client:
    address:
      url: http://localhost:8082/addresses



